### ISSUE TITLE
Not installable with Symfony >= 4.0 

### ISSUE THREAD

**Issue by SimonHeimberg** [dzango/TwigTruncateBundle#2]
Hello,

We can't install the bundle within Symfony 4 (or 5) projects. Could you update your composer.json?
I did not check if there is any other change to do.

Thanks.

**Comment by opichon** [comment]
Hi Simon,

Support for symgony 4 has been added.
We will be adding support for Symfony 5 shortly.

Regards,

**Comment by opichon** [comment]
Support for Symonfy 5 has been added.
